### ISSUE TITLE
Check all groups [using Mozillians API v2]

### ISSUE THREAD

**Issue by nukeador** [Mozilla-cIT/discourse-persona-mozillians#1]
Instead of just checking is_vouched status, we should go through all user groups and add him to them:

https://github.com/LeoMcA/discourse-persona-mozillians/blob/master/plugin.rb#L52

No idea how API reports groups, and I'm guessing is_vouched is a special flag, not a group.

**Comment by LeoMcA** [comment]
Discussion continued here: https://github.com/LeoMcA/discourse-mozillians/issues/3
